DROP TABLE IF EXISTS patients CASCADE;

CREATE TABLE patients (
  id VARCHAR(255) PRIMARY KEY,
  firstname VARCHAR(255),
  lastname VARCHAR(255),
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(20)
);
